# Deploys API to mainnet if attempting to merge to master. Will only trigger if
# a change happened in the api directory, the PR was closed and successfully
# merged to master. There is no `merged to specific branch` event, so we make
# these three checks to make up for it.
name: API Mainnet
on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - 'packages/api/**'
jobs:
  deploy_api:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Echo deploy result'
        run: 'echo deployed to mainnet'
